// css
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import "@mantine/charts/styles.css";
import "./globals.css";
// mantine
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import { ModalsProvider } from "@mantine/modals";
import { theme } from "@/theme";
// other
import type { Metadata } from "next";
import { geistSans, geistMono } from "@/fonts/fonts";
import QueryProvider from "@/providers/QueryClientProvider/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <QueryProvider>
          <MantineProvider theme={theme}>
            <Notifications position="top-right" autoClose={10000} />
            <ModalsProvider>{children}</ModalsProvider>
          </MantineProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
